<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\View\Details $block */
?>

<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')) : ?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <div class="row tab-titles-row">
                <div class="tab-titles-container">
                    <?php foreach ($detailedInfoGroup as $name) : ?>
                        <?php
                        $html = $layout->renderElement($name);
                        if (!trim($html)) {
                            continue;
                        }
                        $alias = $layout->getElementAlias($name);
                        $label = $block->getChildData($alias, 'title');
                        ?>
                        <div class="data item title"
                             data-role="collapsible" id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>">
                            <a class="data switch"
                               tabindex="-1"
                               data-toggle="trigger"
                               href="#<?= $block->escapeUrl($alias) ?>"
                               id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title">
                                <?= /* @noEscape */
                                $label ?>
                            </a>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
            <div class="row tab-content-row">
                <div class="tab-content-container">
                    <?php $isFirstTab = true; ?>
                    <?php foreach ($detailedInfoGroup as $index => $name) : ?>
                        <?php
                        $html = $layout->renderElement($name);
                        if (!trim($html)) {
                            continue;
                        }
                        $alias = $layout->getElementAlias($name);
                        $activeClass = $isFirstTab ? 'active' : '';
                        $displayStyle = $isFirstTab ? '' : 'display: none;';
                        $isFirstTab = false;
                        ?>
                        <div class="data item content <?= $activeClass ?>"
                             style="<?= $displayStyle ?>"
                             aria-labelledby="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title"
                             id="<?= $block->escapeHtmlAttr($alias) ?>"
                             data-role="content">
                            <?= /* @noEscape */
                            $html ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>












